test: remove using BaseController because of rector's error
Error: ] Could not process "tests/system/Router/AutoRouterImprovedTest.php"
         file, due to:
         "System error: "Class 'App\Controllers\BaseController' not found"
         Run Rector with "--debug" option and post the report here:
         https://github.com/rectorphp/rector/issues/new". On line: 16