chore: add "--ignore-platform-req=php" temporarily
Error: Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - vimeo/psalm[5.0.0, ..., 5.13.1] require php ^7.4 || ~8.0.0 || ~8.1.0 || ~8.2.0 -> your php version (8.4.0-dev) does not satisfy that requirement.
    - vimeo/psalm[5.14.0, ..., 5.25.0] require php ^7.4 || ~8.0.0 || ~8.1.0 || ~8.2.0 || ~8.3.0 -> your php version (8.4.0-dev) does not satisfy that requirement.
    - Root composer.json requires vimeo/psalm ^5.0 -> satisfiable by vimeo/psalm[5.0.0, ..., 5.25.0].

Script @composer update --working-dir=utils handling the post-autoload-dump event returned with error code 2
Error: Process completed with exit code 2.