chore: add system/Test/ControllerResponse.php to skip list
It caused an error.

Warning: Undefined array key 1852 in /home/runner/work/CodeIgniter4/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 209

Error: ] Could not process
         "/home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/ControllerResp
         onse.php" file, due to:
         "System error: "PhpParser\Internal\TokenStream::getIndentationBefore():
         Return value must be of type int, null returned"
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line:
         209

Error: Process completed with exit code 1.