Fix CSRF filter does not work when set it to only post
* refactor: case the existence of config files with if statements

To make it easier to know which parts to delete in the future.

* docs: fix PHPDoc explanation

* fix: bug that CSRF cookie is not sent just by calling csrf_hash()

When the CSRF filter was set to POST method, it did not work.

* refactor: replace deprecated method getHeader()

* refactor: extract method

* refactor: extract method

* refactor: extract method

* refactor: use $this->hash instead of $_COOKIE

* test: fix the timing for setting superglobals

* test: fix Cannot modify header information

ErrorException: Cannot modify header information - headers already sent by ...

* style: vendor/bin/rector process

* refactor: ensure instance

It becomes clear that it is `SecurityConfig`.

Co-authored-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

* refactor: ensure instance

It becomes clear that it is `CookieConfig`.

Co-authored-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

* refactor: when $cookie is null, Cookie::setDefaults($cookie) does nothing

* refactor: extract method

* fix: make private extracted methods

* fix: make private added property

* fix: fallback to the local properties

Takes care when a user removes properties in config classes.

* refactor: use $request instead of $_POST

Co-authored-by: Abdul Malik Ikhsan <samsonasik@gmail.com>