fix: add missing property $context
See https://www.php.net/manual/en/class.streamwrapper.php#streamwrapper.props

In PHP 8.2, the following error ocurrs:
ErrorException: Creation of dynamic property CodeIgniter\Test\PhpStreamWrapper::$context is deprecated