test: add missing property in TestHandler
ErrorException: Creation of dynamic property Tests\Support\Log\Handlers\TestHandler::$destination is deprecated